services:

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8080:80"

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - db
    environment:
      - APP_PG_USER=${APP_PG_USER}
      - APP_PG_HOST=${APP_PG_HOST}
      - APP_PG_DATABASE=${APP_PG_DATABASE}
      - APP_PG_PASSWORD=${APP_PG_PASSWORD}
    ports:
      - "3000:3000"

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./db/database.sql:/docker-entrypoint-initdb.d/create_db.sql
